resources:
-  name: source-repo
   type: git
   icon: github
   source: 
     uri: https://github.com/reshmiasish/spring-boot.git
     branch: master
     git_config:
     - name: safe.directory
       value: /tmp/build/get
jobs:
- name: build-and-push
  plan:
  - get: source-repo
    trigger: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: docker, tag: latest}
      inputs:
      - name: source-repo
      outputs:
      - name: built-image
      run:
        path: sh
        args:
        - -exc
        - |
          cd source-repo
          docker build -t reshmi-simple-spring-app .
          docker tag reshmi-simple-spring-app reshmiasish/my-image:latest
          docker push reshmiasish/reshmi-simple-spring-app:latest
   