resources:
-  name: source-repo
   type: git
   icon: github
   source: 
     uri: https://github.com/reshmiasish/spring-boot.git
     branch: master
     git_config:
     - name: safe.directory
       value: /tmp/build/get
- name: docker-image
  type: registry-image
  source:
    repository: reshmiasish/reshmi-simple-spring-app
    username: reshmiasish
    password: do0kcer2024Feb
    tag: latest
jobs:
- name: build-and-push
  plan:
  - get: source-repo
    trigger: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: concourse/oci-build-task}
      inputs:
      - name: source-repo
      outputs:
      - name: image
      params:
        CONTEXT: source-repo/
      run:
        path: build
  - put: docker-image
    params:
      image: image/image.tar
   